dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.2"

dotenv: .env

wallets:
  executor_addr: ${EXECUTOR}
  seller_addr: ${SELLER}
  buyer_addr: ${BUYER}
  owner_addr: ${OWNER}
